server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:thy
    username: sa
    password: thy.admin!*.
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  data:
    elasticsearch:
      cluster-names: thy-elastic-search
      cluster-node: localhost:9200
springfox:
  documentation:
    swagger-ui:
      enabled:true
resilience4j.ratelimiter:
  instances:
    basic:
      limitForPeriod: 100
      limitRefreshPeriod: 1m
      timeoutDuration: 3s
      registerHealthIndicator: true
      eventConsumerBufferSize: 100